### ISSUE TITLE
Double Text on Notches

### ISSUE THREAD

**Issue by 1Map** [Paroca72/sc-widgets#14]
How would I go about creating a gauge that has Degrees Fahrenheit text on the outside and Degrees Celsius text in the inside ?

**Comment by Paroca72** [comment]
Hello,

In the [gauge](https://github.com/Paroca72/sc-gauges/blob/master/raw/sc-gauge/ScGauge.md) you can add all features you want.
In your case you must add another [ScWriter](https://github.com/Paroca72/sc-gauges/blob/master/raw/sc-writer/ScWriter.md) (Inherited from [ScFeature](https://github.com/Paroca72/sc-gauges/blob/master/raw/sc-feature/ScFeature.md)) and set it as you need.

The default writer you can set by the XML instead the new writer you will add so:
ScWriter extraWriter = (ScWriter) gauge.addFeature(ScWriter.class);

And configured follow the documentation ([ScWriter](https://github.com/Paroca72/sc-gauges/blob/master/raw/sc-writer/ScWriter.md))

Please let me know if you more help

Bye
Sam

**Comment by Paroca72** [comment]
I realized now that you are using an discontinued repository..
Please refer to [sc-gauge repository](https://github.com/Paroca72/sc-gauges)

Thanks
