### ISSUE TITLE
Animation on Gauges

### ISSUE THREAD

**Issue by 1Map** [Paroca72/sc-widgets#15]
How would I go about to show animation between value changes on a gauge?

**Comment by Paroca72** [comment]
Hello,

It is a quite simple as the [gauge](https://github.com/Paroca72/sc-gauges/blob/master/raw/sc-gauge/ScGauge.md) already have associated to the (high and low) values an Animator object.

So you just need to get the Animator from the guage as follow (high or low, usually high):
Animator animation = gauge.getHighValueAnimator();

And assign a duration in millisecond:
animation.setDuration(500);

Let me know is this solve your case

Bye
Sam

**Comment by Paroca72** [comment]
I realized now that you are using an discontinued repository..
Please refer to [sc-gauge repository](https://github.com/Paroca72/sc-gauges)

Thanks
