### ISSUE TITLE
setFillingColors not include this lib

### ISSUE THREAD

**Issue by ulaslaslas** [Paroca72/sc-widgets#5]
Hi, nice lib!

But doesn't work setFillingColors methods. 

Can you help us?

![image](https://cloud.githubusercontent.com/assets/12948351/20138340/84c16812-a688-11e6-8e23-6fa30ae00b0c.png)

**Comment by ulaslaslas** [comment]
i resolve this problem in xml side.

Add this line in widget.
sc:scc_stroke_colors="#97B329|#A9CB2A|#D4E935|#F1DD31|#FBCB2E|#F3A328|#F18C23|#F3341E|#F51319"

![image](https://cloud.githubusercontent.com/assets/12948351/20139016/ab086116-a68c-11e6-8f7a-c96cb9c4edf5.png)

**Comment by Paroca72** [comment]
Hello,

Sorry for the late reply. 
Thanks for advise.. I will check as soon as possible.

Bye

**Comment by Paroca72** [comment]
Hello,

I have updated the examples using the last version methods.

Thanks.
