### ISSUE TITLE
Left arc of gauge cut after setHighValue method

### ISSUE THREAD

**Issue by Pravind-Clarion** [Paroca72/sc-widgets#9]
Below is my custom class for displaying gauge view by inheriting ScArcGauge class.

public class MyArcGauge extends ScArcGauge implements Runnable{
    private Context context;
    Thread thread;
    private Paint paint;
    private Bitmap mBitmap;

    public MyArcGauge(Context context) {
        super(context);
        init(context);
    }

    public MyArcGauge(Context context, AttributeSet attrs) {
        super(context, attrs);
        init(context);
    }

    public MyArcGauge(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init(context);
    }
    private void init(Context context){
        this.context = context;
        thread = new Thread(this);
        paint = new Paint();
        thread.start();
    }
    @Override
    protected void dispatchDraw(Canvas canvas) {
        super.dispatchDraw(canvas);
    }

    @Override
    public void run() {
        for(int i=1;i<=150;i++){
            final int finalI = i;
            ((Activity)context).runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    // Set the center pivot for a right rotation
                    setHighValue(finalI + 1,0,180);
                }
            });
            try {
                Thread.sleep(20);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
}

I am researching on how we can animate needle in real time using this library, I succeed in to achieve that but my left side of gauge cut a little bit after calling setHighValue value as shown in the 
![screenshot_20170508-094515](https://cloud.githubusercontent.com/assets/28536951/25809904/194b70fa-342c-11e7-879c-dedbeef42192.png)
screenshot.

**Comment by Paroca72** [comment]
Hello,

With a Thread are you trying to create an animation?
If yes.. you can animate the high (and the low) value in a more simple way.

ScArcGauge inherits ScGauge and you can use the method getHighValueAnimator() to get the Animator (https://developer.android.com/reference/android/animation/Animator.html) object to animate the gauge value (https://github.com/Paroca72/sc-widgets/blob/master/raw/sc-gauge/ScGauge.md).

Is enough to set the Animator duration (setDuration) to have an smooth animation and you can play also with the interpolator (setInterpolator)  if you want change the kind of animation..

Else, if you need to use a Thread for another reason, please let me know and will investigate.

Sam

**Comment by Pravind-Clarion** [comment]
Sure I will try with Animator object but do you have any idea why that left edge cut after setting high values? My initial guess is it is default marker like thing.

**Comment by Paroca72** [comment]
Hello,

Kindly can you send me the source code of your demo (SSSDemo)?

Sam

**Comment by Paroca72** [comment]
All the project (SSSDemo)...

**Comment by Pravind-Clarion** [comment]
GaugeViewActivity.java

public class GaugeViewActivity extends AppCompatActivity{
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_gauge_view);
        initSCWidget();
    }
    private void initSCWidget(){
        final MyArcGauge gauge = (MyArcGauge) findViewById(R.id.gauge);
        final ImageView pointer = (ImageView) findViewById(R.id.drag_pointer);
        pointer.setVisibility(View.VISIBLE);

        gauge.setHighValue(0);
        final Animator animator = gauge.getHighValueAnimator();
        animator.setTarget(pointer);

        // Each time I will change the value I must write it inside the counter text.
        gauge.setOnEventListener(new ScGauge.OnEventListener() {
            @Override
            public void onValueChange(float lowValue, float highValue) {
                // Write the value
                final float angle = gauge.percentageToAngle(highValue);
                pointer.setRotation(angle);
            }
        });
    }
}

activity_gauge_view.xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="in.co.clariontechnologies.sssdemo.GaugeViewActivity"
    android:orientation="vertical">
    <FrameLayout
        android:layout_width="300dp"
        android:layout_height="wrap_content">
        <in.co.clariontechnologies.sssdemo.custom.MyArcGauge
            android:id="@+id/gauge"
            xmlns:sc="http://schemas.android.com/apk/res-auto"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="top|center_horizontal"
            android:padding="40dp"
            sc:scc_angle_start="180"
            sc:scc_angle_sweep="180"
            sc:scc_stroke_size="40dp"
            sc:scc_stroke_colors="#03A409|#FFF506|#EB0100"
            sc:scc_notches="10"
            sc:scc_notches_size="0dp"
            sc:scc_notches_length="20dp"
            sc:scc_notches_color="#004e4e4e"
            sc:scc_text_align="center"
            />
        <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/drag_pointer"
            android:id="@+id/drag_pointer"
            android:visibility="gone"
            android:layout_gravity="bottom|center_horizontal" />
    </FrameLayout>
</LinearLayout>

drag_pointer.png
![drag_pointer](https://cloud.githubusercontent.com/assets/28536951/25886585/e35a0fbe-357b-11e7-94f4-92764a080160.png)

**Comment by Pravind-Clarion** [comment]
Can't upload the whole project but above is all information that is related to gauge view implementation.

**Comment by Paroca72** [comment]
Hello,

I found the issue but I still not found the solution.. let me more time..

I prepared a code with the right way to use the animation and I activated the path touch event so you will see the indicator move when you press on the curve..

You will note than using the library, in this example, not produce any graphics issue but the issue appears just when use to call directly the setHighValue method and sound very strange because, at the end, the touch event call the same method.. I will investigate soon and let you know..

Note: please use the drag_pointer.png enclosed as the short way to have a correct rotation. Otherwise if you not have a square image you must setting the right rotation center by the code.. 

[test.zip](https://github.com/Paroca72/sc-widgets/files/989604/test.zip)

Sam

**Comment by Pravind-Clarion** [comment]
Thanks for your guidance and support.

**Comment by Paroca72** [comment]
Hello,

I realsed a new version 2.1.4 that should resolve your issue.. but I have some problem with jitpack.io and I don't know if can be downloaded through gradle..

Kindly if you can try to download from gradle or manually and let me know.

Bye

**Comment by Pravind-Clarion** [comment]
Thank you, This resolved my issue and animation provided by you also working smooth.

**Comment by Paroca72** [comment]
Hello.

Please download the new version 2.1.5
This should be resolve a problem calling the  ScDrawer.onDraw.

Thanks
Bye

**Comment by Pravind-Clarion** [comment]
Thanks.
